version: '3.2'
services:
  rabbitmq:
    image: 'rabbitmq:3.7.2-management'
    volumes:
      - './rabbitmq/data:/var/lib/rabbitmq/mnesia'
      - './rabbitmq/logs:/var/log/rabbitmq'
    ports:
      - '5672:5672'
      - '5671:5671'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
